FROM node:20-alpine AS base

WORKDIR /usr/src/app

COPY package*.json ./
COPY core ./core/

FROM base AS dependencies
WORKDIR /usr/src/app
COPY --from=base /usr/src/app/package*.json ./
RUN apk add --no-cache build-base g++ cairo-dev jpeg-dev pango-dev giflib-dev

RUN npm install

FROM base AS release
WORKDIR /usr/src/app
COPY --from=dependencies /usr/src/app/node_modules ./node_modules
COPY . .

EXPOSE 3002

CMD [ "npm", "run", "start:nas" ]